project_id = "acatkjjhveameiywcurn"

[functions.extract-ingredients]
verify_jwt = false

[functions.generate-recipe]
verify_jwt = false

[functions.generate-recipe-image]
verify_jwt = false

[functions.import-nevo-data]
verify_jwt = false

[functions.search-nevo-ingredients]
verify_jwt = false

[functions.optimize-recipe-nutrition]
verify_jwt = false
